---
# Template configuration files for openscap

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ openscap_templates_copy }}"
  when: openscap_copy_templates
